<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected $touches = ['project'];

    // when a task will be created, this will be called
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static ::created(function($task){

            $task->project->recordActivity('created_task');

        });


        static ::updated(function($task){

            if (!$task->completed) return;

            $task->project->recordActivity('completed_task');

        });

    }

    // when task is completed,
    public function complete(){
        $this->update(['completed' => true]);
    }

    public function project(){

        return $this->belongsTo(Project::class);
    }

    public function path(){

        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }
}
